FROM node:12-alpine as node

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#STAGE2

FROM nginx:1.17.3-alpine

COPY --from=node /usr/src/app/dist/E-bidder /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf